<div class="col-md-12">
	<p>If you are a Human Resources manager or a corporate executive who is looking to lower health care costs within your organization by reducing the chronic disease burden among your employees, then Inland Empire Weight Loss would like to help.  We offer a wellness program designed to reduce and improve obesity related chronic conditions through improvements in lifestyle, diet, and exercise.   We can work with an individual’s current health care provider to design a program that improves overall health and reduces their medication burden. </p>
	<p> If your company offers a shared or full risk environment in providing health care benefits to your employees, then a wellness program such as ours will offer immediate benefits in reducing healthcare pharmacy, medical, and hospital claims.  Even if you are not in a shared/full risk environment, employees who are healthier have a decreased disease burden which results in a lowering of medical claims loss and a decrease in corporate health insurance rates.  Additionally, if your employees have a reduced weight and improvements in their health, there will be a decrease in absenteeism and an increase in productivity.</p>

	<p>Dr. Knopke is double board certified in <a href="http://www.abom.org" title="Obesity Medicine" target="_blank">Obesity Medicine</a> and <a href="http://www.theabfm.org" target="_blank" title="Family Medicine">Family Medicine</a>.  He is a leader in the field of Obesity Medicine.  He has been elected and currently serves as a member of the <a href="http://www.asbp.org/about/boardoftrustees.html" target="_blank" title="Board of Trustees">Board of Trustees</a> for the American Society of Bariatric Physicians (ASBP) (link to www.asbp.org) and is an Assistant Professor in Family Medicine at the <a href="http://medschool.ucr.edu/about/directory.html" target="_blank" title="University Of California Riverside School Of Medicine">University Of California Riverside School Of Medicine</a>.  Additionally he is a member of many other related <a href="link to http://www.inlandempireweightloss.com/people.php#recognition" title="Medical Associations that Dr. Knopke is a member of">Medical Associations</a>.  He has spoken to and taught other medical professionals both locally and nationally on topics related to Obesity Medicine.  He also offers a 4th year elective rotation to UCR medical students interested in pursuing a career in the field of Obesity Medicine.  He is an active participant in designing continuing medical education (CME) programs on the topic of obesity medicine through <a href="http://www.asbp.org/asbpmembership/committees.html" title="ASBP" target="_blank">ASBP</a>.</p>  

	<p>Further information on Dr. Knopke can be found on his <a href="link to https://www.linkedin.com/profile/preview?locale=en_US&trk=prof-0-sb-preview-primary-button" target="_blank" title="Dr. Carl Knopke's LinkedIn page">LinkedIn page</a>.  Interested parties are invited to send an email to Dr. Knopke at <a href="mailto:drknopke@inlandempireweightloss.com" title="Email Dr. Carl Knopke">drknopke@inlandempireweightloss.com</a> or to call the office directly at 951-774-2723 and ask to speak to Dr. Knopke about options for the corporate program.  Dr. Knopke can meet individually with HR managers or other corporate decision makers on a one on one basis to discuss options should there be interest in our program.  
	We look forward to making your employees healthier.</p>
	<hr>
	<h4>For Providers</h4>
	<p>Inland Empire Weight Loss is currently accepting consultation requests in the area of Obesity Medicine.  Dr. Knopke is double Board Certified in the field of Obesity Medicine by the ABOM (link to www.abom.org) and in Family Medicine (link to www.thabfm.org).  The specialty board of Obesity Medicine was established in 2011.  Further information on this board can be found <a href="http://abom.org/history/" target="_blank" title="American Board of Obesity : History">here</a>.  Upon request of a consultation, you as a provider will receive a consultation letter from Dr. Knopke or Lesley Laird, PA-C.  If there are questions in regards to the plan, Dr. Knopke will be more than happy to discuss any concerns you may have on the phone.  For an overview of the assessment and treatment techniques, I would refer you to the <a href="documents/ASBPGuidelinesForOverweightAndObesityEvaluationManagement.pdf" title="ASBP Guidelines For Overweight And Obesity Evaluation Management" target="_blank"><i class="fa fa-file-pdf-o"></i> ASBP Obesity Algorithm</a>.  Our aim is to diminish the burden of chronic disease in the individual affected by Obesity.  We accept most major PPO health insurances as well as Medicare.  We accept consultations for the following requests:</p>
	<ul>
		<li>Weight loss (Adults and Children)</li>
		<li>Diabetes and other diseases related to insulin resistance such as:</li>
		<li>Metabolic syndrome/Prediabetes/Insulin Resistance</li>
		<li>PCOS</li>
		<li>Hypertension</li>
		<li>Fatty liver, NAFLD/NASH</li>
		<li>Hyperlipidemia</li>
		<li>Pre and post-bariatric surgical evaluations</li>
		<li>Migraine headaches (tends to improve with weight loss and dietary change)</li>
		<li>Obesity related psychiatric disorders such as:</li>
		<li> <a href="https://www.nationaleatingdisorders.org/binge-eating-disorder" target="_blank" title="Binge Eating Disorder">Binge Eating Disorder</a></li>
		<li><a href="http://www.health.harvard.edu/blog/nighttime-overeating-can-throw-weight-and-health-out-of-sync-201309136658" target="_blank" title="Night Eating Syndrome">Night Eating Syndrome</a></li>
		<li>Major Depression (when related to obesity)</li>
		<li>Generalized Anxiety Disorder (when related to Obesity</li>
		<li>Bipolar Disorder (when related to Obesity)</li>
		<li>Addictions to food/carbohydrates</li>
		<li>Obstructive Sleep Apnea (to manage their weight)</li>
		<li>Osteoarthritis: weight loss for symptomatic improvement and to help with preoperative weight loss for total knee and hip arthroplasty.</li>
		<li>Ventral hernias that require preoperative weight loss</li>
		<li>Prepregnancy weight loss and help in Obesity related fertility issues (such as PCOS)</li>
	</ul>
	<hr>
	<p>Dr. Knopke is a leader in the field of Obesity Medicine.  He has been elected and currently serves as a member of the <a href="http://www.asbp.org/about/boardoftrustees.html" title="_blank" title="Board of Trustees">Board of Trustees</a> for the American Society of Bariatric Physicians (ASBP) (link to www.asbp.org) and is an Assistant Professor in Family Medicine at the <a href="http://medschool.ucr.edu/about/directory.html" target="_blank" title="University Of California Riverside School Of Medicine">University Of California Riverside School Of Medicine</a>.  Additionally he is a member of many other related <a href="http://www.inlandempireweightloss.com/people.php#recognition" title="Medical Associations that Dr. Knopke is a member of">Medical Associations</a>.  He has spoken to and taught other medical professionals both locally and nationally on topics related to Obesity Medicine.  He also offers a 4th year elective rotation to UCR medical students interested in pursuing a career in the field of Obesity Medicine.  He is an active participant in designing continuing medical education (CME) programs on the topic of <a href="http://www.asbp.org/asbpmembership/committees.html" target="_blank" title="Obesity Medicine">Obesity Medicine</a> which are designed to educate other Obesity Medicine providers around the country on various topics in Obesity Medicine.  He is also an instructor for the ASBP for their board preparatory course to help other physicians study for and pass their Obesity Medicine Board exam.</p>

	<p>Should you have any questions about the nature of our program, Dr. Knopke can be reached at <a href="mailto:drknopke@inlandempireweightloss.com" title="Email Dr. Carl Knopke">drknopke@inlandempireweightloss.com</a> or please call the office directly at 951-774-2723 and ask to speak to Dr. Knopke.</p>
</div>