<div class="col-md-12">
	<p>The CDC notes that as of 2014, 9.6% of adults in the state of California are diabetic.   Nationwide, 28% of those who are diabetic are not aware that they are diabetic.   The incidence of diabetes rises with age.  16% percent of those between the ages of 45-64 are diabetic and over the age of 64, 25.9% of the population is diabetic.   37% of U.S. Adults over the age of 20 had Prediabetes and 51% of those 65 and older has Prediabetes.   <a href="https://www.aace.com/publications/algorithm" target="_blanks" title="The American Association of Clinical Endocrinologists">The American Association of Clinical Endocrinologists</a> recommends <a href="https://www.aace.com/files/aace_algorithm_slides.pptx" target="_blank" title="lifestyle modification PowerPoint">lifestyle modification <i class="fa fa-file-powerpoint-o"></i></a> including medically assisted weight loss as the first line of therapy that should be done for both Diabetes and Prediabetes.  Most physicians are not experienced with medically assisted weight loss. However, at Inland Empire Weight Loss, this is our specialty.  We are experienced in a variety of techniques to help you to achieve medically assisted weight loss.  </p>
	<p>The concern in diabetes is that the disease process starts well before the diagnosis of diabetes.  In <a href="http://outpatient.aace.com/type-2-diabetes/clinical-presentation-of-type-2-diabetes-mellitus" target="_blank" title="Clinical Presentation of Type 2 Diabetes Mellitus">this slide</a> from the American Association of Clinical Endocrinologists, you can see the natural progression of diabetes.</p>
	<hr>
	<p>As you can see, as much as 10 (or more) years prior to the onset of diabetes, insulin levels are rising and insulin resistance rises as well. This tends to occur many years before the onset of hyperglycemia either from a fasting state or from postprandial glucose.  As the blood sugar continues to climb, the glucose actually becomes toxic to the pancreas which causes glucose to rise further and faster.  This tipping point is usually occurring right when the disease process acquires the label of diabetes.   Looking at the lower area of this chart, you can also see that the microvascular complications such as diabetic kidney and retina disease as well as the macrovascular complications such as atherosclerosis leading to heart attack and stroke start well before the point where insulin resistance can be called diabetes.</p>
	<p>The natural progression of the disease process tends to follow this path:</p>
	<p>Insulin resistance  Prediabetes  Metabolic Syndrome  Early Diabetes  Late Diabetes</p>
	<p>Insulin resistance is marked by elevated insulin levels, weight gain, and presence of small dense LDL particles leading to atherogenesis which leads to the onset of cardiovascular disease.  Fasting blood sugars and average blood sugars are often normal at this point.  Your doctor will probably tell you that your labs are normal.</p>
	<p>Prediabetes is marked by slowly rising glucose levels following meals.  Your doctor may order a test called a HbA1c which may be slightly elevated (between 5.7-6.4) and your fasting blood sugar will generally be in the upper 80’s to low 90’s which is usually called normal.  Many doctors will often say that these labs are “normal”.</p>

	<p>Metabolic Syndrome is really a constellation of findings marked by:</p>
	<ul>
		<li>Fasting Blood Sugar of 100 or greater</li>
		<li>Waist measurements &ge; 35 inches in women, &ge; 40 inches in men</li>
		<li>Blood pressure readings of &ge; 130/85</li>
		<li>Triglycerides &ge; 150</li>
		<li>HDL &lt; 50 in women and &lt; 40 in men</li>
	</ul>
	<p>Early Diabetes is marked by a fasting glucose of 126 or greater or a hemoglobin A1c of 6.5 or above.  At this point, younger patient will still retain much of their pancreatic function but older individuals will have a diminished pancreatic function.  There has already been a significant amount of damage from atherosclerosis both to larger vessels (heart and brain) and small vessels (eyes and kidney).</p>
	<p>Late Diabetes is marked by very high blood sugars both before and after a meal, increased lability in which blood sugar numbers will seem to be “all over the place”, very poor pancreatic function and increasing vascular pathology.  Most of the symptoms that are often discussed with diabetes such as thirst, increased hunger, and heavy urination are not realized until this point.</p>
	<p>As part of your assessment we can determine where you are in the continuum of insulin resistance. We have experience treating people from the early phases of insulin resistance all of the way to late uncontrolled diabetes.  We have been successful in treating people with diabetes and getting them off of their medications or significantly improving their medication mix such as getting them off of insulin.  If your doctor has told you that you will never be off of your diabetic medications or that you will always be on insulin, we do not find this to be true. We are often able to get people onto fewer diabetic medications, including those treated with insulin. </p>
</div>